#!/usr/bin/env python3
"""Regenerate rituals/INDEX.md + docs/rituals.json from all TOML ritual files.

Reads every .toml under rituals/, extracts id / name / description / schedule /
timezone / category / kind / enabled / command, and writes:
  - rituals/INDEX.md  (human catalog, grouped by category)
  - docs/rituals.json (machine-readable feed for the GitHub Pages gallery)
Pure stdlib (tomllib from Python 3.11+).
"""
from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RITUALS = ROOT / "rituals"
OUT = RITUALS / "INDEX.md"
JSON_OUT = ROOT / "docs" / "rituals.json"
SCAN_IN = ROOT / "docs" / "scan.json"


def main() -> int:
    if not RITUALS.is_dir():
        print(f"no rituals dir at {RITUALS}", file=sys.stderr)
        return 1
    scan_by_path: dict[str, dict] = {}
    if SCAN_IN.exists():
        scan = json.loads(SCAN_IN.read_text())
        scan_by_path = {r["path"]: r for r in scan.get("results", [])}

    by_cat: dict[str, list[dict]] = {}
    for toml_path in sorted(RITUALS.rglob("*.toml")):
        with toml_path.open("rb") as fh:
            data = tomllib.load(fh)
        jobs = data.get("jobs") or []
        if not jobs:
            print(f"skip (no [[jobs]]): {toml_path}", file=sys.stderr)
            continue
        job = jobs[0]
        cat = job.get("category") or toml_path.parent.name
        rel = toml_path.relative_to(ROOT).as_posix()
        audit = scan_by_path.get(rel, {})
        by_cat.setdefault(cat, []).append(
            {
                "id": job.get("id", toml_path.stem),
                "name": job.get("name", job.get("id", toml_path.stem)),
                "description": job.get("description", "").strip(),
                "schedule": job.get("schedule", ""),
                "timezone": job.get("timezone", "UTC"),
                "kind": job.get("kind", "shell"),
                "enabled": bool(job.get("enabled", False)),
                "timeout_sec": job.get("timeout_sec"),
                "author": audit.get("author", job.get("author", "kdairatchi")),
                "trust": audit.get("trust", job.get("trust", "core")),
                "permissions": audit.get("permissions", []),
                "required_env": audit.get("required_env", []),
                "scan_status": audit.get("status", "UNKNOWN"),
                "warnings": audit.get("warnings", []),
                "path": rel,
            }
        )

    lines: list[str] = []
    lines.append("# Rituals index\n")
    lines.append("*Auto-generated by `scripts/gen-index.py` — do not edit by hand.*\n")
    total = sum(len(v) for v in by_cat.values())
    lines.append(f"**{total} rituals across {len(by_cat)} categories.**\n")
    lines.append(
        "| Category | Count | IDs |\n| --- | ---: | --- |"
    )
    for cat in sorted(by_cat):
        ids = ", ".join(f"`{r['id']}`" for r in sorted(by_cat[cat], key=lambda r: r["id"]))
        lines.append(f"| **{cat}** | {len(by_cat[cat])} | {ids} |")
    lines.append("")

    for cat in sorted(by_cat):
        lines.append(f"## {cat}/\n")
        lines.append("| ID | Kind | Schedule (TZ) | Description |")
        lines.append("| --- | --- | --- | --- |")
        for r in sorted(by_cat[cat], key=lambda r: r["id"]):
            sched = f"`{r['schedule']}` ({r['timezone']})" if r["schedule"] else "—"
            desc = r["description"].replace("|", "\\|") or r["name"]
            lines.append(f"| [`{r['id']}`]({r['path']}) | `{r['kind']}` | {sched} | {desc} |")
        lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} — {total} rituals / {len(by_cat)} categories")

    flat: list[dict] = []
    for cat in sorted(by_cat):
        for r in sorted(by_cat[cat], key=lambda r: r["id"]):
            flat.append(
                {
                    "id": r["id"],
                    "name": r["name"],
                    "description": r["description"],
                    "category": cat,
                    "kind": r["kind"],
                    "schedule": r["schedule"],
                    "timezone": r["timezone"],
                    "timeout_sec": r.get("timeout_sec"),
                    "author": r.get("author", "kdairatchi"),
                    "trust": r.get("trust", "core"),
                    "permissions": r.get("permissions", []),
                    "required_env": r.get("required_env", []),
                    "scan_status": r.get("scan_status", "UNKNOWN"),
                    "warnings": r.get("warnings", []),
                    "path": r["path"],
                    "install_cmd": f"./install.sh {r['path']}",
                    "github_url": f"https://github.com/kdairatchi/CronLord-Grimoire/blob/main/{r['path']}",
                }
            )
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(
        json.dumps(
            {
                "generated_at": None,
                "total": total,
                "categories": sorted(by_cat),
                "rituals": flat,
            },
            indent=2,
        )
        + "\n"
    )
    print(f"wrote {JSON_OUT.relative_to(ROOT)} — {total} rituals (JSON feed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
